# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "主页"
  [zh.params]
    description = "Site description in Chinese..."
  [[zh.menu.main]]
    name = "关于"
    url = "#about"
    weight = 1

  [[zh.menu.main]]
    name = "技能"
    url = "#skills"
    weight = 21

  [[zh.menu.main]]
    name = "教育"
    url = "#eduaction"
    weight = 31

  [[zh.menu.main]]
    name = "实习经验"
    url = "#experience"
    weight = 40

  [[zh.menu.main]]
    name = "项目"
    url = "#projects"
    weight = 50

